### ISSUE TITLE
Move redux directories into src directory

### ISSUE THREAD

**Issue by lenaten** [tj/frontend-boilerplate#12]

**Comment by tj** [comment]
maybe some day, but I kind of like them at root. I plan on using a Go server so it'll be in a separate repo

**Comment by lenaten** [comment]
sure. what about rename 'src' to something like root / static / public?
src could be confusing for side directory with two files..

**Comment by tj** [comment]
Ah yea agreed there, this was derived from another boilerplate originally, missed that awkward name
