### ISSUE TITLE
Linting with Webpack

### ISSUE THREAD

**Issue by d2s** [tj/frontend-boilerplate#18]
Ability to check file structure with JavaScript and CSS linters would be useful for many.

[Linting in Webpack](http://survivejs.com/webpack_react/linting_in_webpack/) –guide has details on how to setup those to Webpack –based project.
- [ESLint](http://survivejs.com/webpack_react/linting_in_webpack/#setting-up-eslint) with Webpack.
- [JSCS](http://survivejs.com/webpack_react/linting_in_webpack/#checking-javascript-style-with-jscs) with `jscs-loader` for Webpack support.
- [stylelint](http://survivejs.com/webpack_react/linting_in_webpack/#linting-css) allows to lint CSS and can be used with Webpack through postcss-loader.

Also:
- [EditorConfig](http://survivejs.com/webpack_react/linting_in_webpack/#editorconfig) allows you to maintain a consistent coding style across different IDEs and editors.

**Comment by tj** [comment]
I'll probably just use a jsfmt in my editor. I'm just a one-man team so that's not a huge concern for now. I'll  check em out if that changes. cheers
