### ISSUE TITLE
Redux router

### ISSUE THREAD

**Issue by tj** [tj/frontend-boilerplate#2]
Too many to choose from wtf, try a few and add one

https://github.com/rackt/redux-simple-router

**Comment by anthonyshort** [comment]
Just make the route state like everything else :P 
1. On url change you trigger a `navigate` action
2. Transform the url into a state object
3. Change the browser url as a side-effect

Welcome to the weird world of front-end haha

**Comment by tj** [comment]
It is lovely haha. I haven't dug into any of the routers yet but I'm assuming they add some sort of value, or just more weird abstractions haha. I'm way past the days of trying to have elegant front-end, I just want to get shit in there and work on real things

**Comment by anthonyshort** [comment]
Exactly. It's impossible to make it _really_ nice. Everything sucks.

**Comment by tj** [comment]
![](http://s7.hostingkartinok.com/uploads/images/2015/01/081e30e5e937cf2e2a29cf02617151ff.jpg)

**Comment by ashaffer** [comment]
My preference on this is to store only the url itself in state, and materialize everything from that as you render. So you have some high-level router component that takes the current url as a prop, parses it, and returns the correct view. This has the additional benefit of nesting and composing simply.

Something like [enroute](https://github.com/lapwinglabs/enroute) is good for that.

**Comment by tj** [comment]
Yea that sounds like a good approach to me too, I'll take a peek

**Comment by aweary** [comment]
That sounds like a problem that [`react-router`](https://github.com/rackt/react-router) has already solved. I think for a boilerplate repo it would be the best choice for routing since its essentially the de-facto standard for routing with react. As far as redux routing integration, `redux-simple-router` is a good choice in my experience.

**Comment by VinSpee** [comment]
another vote here for `react-router` to manage the actual business of routing and `redux-simple-router` to expose it to your state tree. I think redux-simple-router is a very simple layer to add on top that only does what you'd expect.

**Comment by gaearon** [comment]
redux-simple-router + react-router ftw

**Comment by brianc** [comment]
+1 to what @gaearon @VinSpee, and @Aweary said.

**Comment by tleen** [comment]
[Calypso](https://github.com/Automattic/wp-calypso) uses [page.js](https://github.com/visionmedia/page.js), given your familiarity with it did you already reject it for consideration?

**Comment by gaearon** [comment]
page.js is cool but it doesn't solve nested UIs so you have to do it on your own.
Nested routing is requirement for pretty much any modern app.
This is why I like react-router.

**Comment by tj** [comment]
haha yea agreed, page is a little dated, anything that integrates directly with react is :+1:  just stuff you'd have to do anyway

**Comment by gaearon** [comment]
While we're at it check out RR 2.0 beta API. It's way more straightforward and fixes rough edges of 1.x.

**Comment by BobDigi420** [comment]
Yes finally
