### ISSUE TITLE
Getting errors when making a change in any file

### ISSUE THREAD

**Issue by kitze** [tj/frontend-boilerplate#33]
I've tried using node 0.\* , 4._, 5._ and i still get the error. 

I'm just adding a simple code change like a console.log anywhere in the code and when i save the edited file i'm getting this notification https://i.imgur.com/7QuncHe.png and also this in the console https://i.imgur.com/xbuP0qL.png

So when i try to add a todo i cannot, redux doesn't work anymore and i need to full page refresh. 

I'm using Chrome Canary but it's the same behaviour in regular chrome. What's going on?

**Comment by tj** [comment]
Hmm I've had that issue intermittently, I'm not sure what the issue is off hand though sorry! I haven't hit it enough to dive in yet

**Comment by kitze** [comment]
I hit it everytime i click save and the app doesn't work anymore, which renders this boilerplate pretty useless... 😔

**Comment by kitze** [comment]
@tj i can confirm that this was caused by the redux devtools chrome extension. When i removed it i don't hit the error anymore. But now i don't have the devtools even if i press ctrl+h.

**Comment by tj** [comment]
seems fine to me, if we can find that it's an issue with something configured here we can reopen
