### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by woliveiras** [tj/frontend-boilerplate#34]
It's interesting create a [.editorconfig](http://editorconfig.org/) for the project?

**Comment by tj** [comment]
Nahh, too many dotfiles looks overwhelming for people I think, at least that's how I feel when I see like 15 in the repo root. It's easy for me, 2 spaces for everything except Go and Makefiles which require tabs

**Comment by woliveiras** [comment]
Really. :smile:

So I'll close the issue, ok?

**Comment by PatrickJS** [comment]
dat dotfile fatigue

**Comment by hstonge** [comment]
I guess savvy developers will indeed be able to handle code formatting themselves, but it's hard to refuse a nice auto-format magic from your IDE :)

**Comment by woliveiras** [comment]
@hstonge :+1: :smile:

**Comment by tj** [comment]
I guess it has enough options to be worth it-ish haha, kinda, most are kind of implied these days, trimming trailing whitespace etc is a no-brainer

**Comment by brandonb927** [comment]
@tj you'd be surprised at how many developers I meet who don't have those (auto-trim trailing whitespace, auto-insert newline at EOF, etc) baked into their editors :\

**Comment by mikaa123** [comment]
I'm not convinced anymore by the usefulness of `.editorconfig` files. Most of the time they just sit there. However I think having rules for linting would be great!

Maybe we could start by extending [eslint config rakt](https://github.com/rackt/eslint-config-rackt) and incrementally add the rules we want?

**Comment by thebigredgeek** [comment]
+1 on the linting.  I'll submit a PR with an eslint boilerplate.  We can work off of that

**Comment by thebigredgeek** [comment]
@tj eslint boilerplate is blocked by https://github.com/tj/frontend-boilerplate/pull/47
We will want to use babel-eslint for the linting.  It is the de-facto way of doing this now-a-days

**Comment by thebigredgeek** [comment]
https://github.com/tj/frontend-boilerplate/pull/48
