### ISSUE TITLE
react-hot-loader should be dev-dependency not an app dependency

### ISSUE THREAD

**Issue by aziz** [tj/frontend-boilerplate#37]

**Comment by tj** [comment]
I suppose they're all dev dependencies really, only thing that gets into prod is a build

**Comment by aziz** [comment]
You wanna say, you're not gonna make it isomorphic and render it server side in near future :wink:

**Comment by tj** [comment]
nope haha

**Comment by thebigredgeek** [comment]
This is resolved here> https://github.com/tj/frontend-boilerplate/pull/47

**Comment by tj** [comment]
moved them all
