### ISSUE TITLE
CSS color functions

### ISSUE THREAD

**Issue by tj** [tj/frontend-boilerplate#4]
handy, miss these

**Comment by epilande** [comment]
There is [cssnext](http://cssnext.io/features/#color) & [rucksack](http://simplaio.github.io/rucksack/docs/#hexrgba). Or why not both? 
They both provide useful utilities.

**Comment by tj** [comment]
just going to cherry-pick some things I want

**Comment by tj** [comment]
nvm I like most of rucksack, adding!
