### ISSUE TITLE
npm build not work

### ISSUE THREAD

**Issue by janjon** [tj/frontend-boilerplate#58]
npm build not work

**Comment by tj** [comment]
works fine for me (note that it's `npm run build` not `npm build`), please add an error message if it still doesn't work

**Comment by basejs** [comment]
maybe your NODE_ENV is bad, you can try: 
npm install cross-env --save-dev
and edit it
"build": "cross-env NODE_ENV=production webpack --progress --colors"

**Comment by danielMensah** [comment]
@basejs could you please specify which part of the cross-env file to edit? maybe an example of the file would be great.
